---
name: Release
on:
  release:
    types:
      - published

env:
  PYTHONUNBUFFERED: 1

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@d9c158044abff69356475ff82b1f99b78dbd9d93 # 7.0.0
    with:
      slackChannel: C02E6L5C01H # squad-devex-private
