---
name: Release
on:
  release:
    types:
      - published

env:
  PYTHONUNBUFFERED: 1

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@a522ea7c2e3c4bd8599c1826eed711aff870c826 # 6.2.5
    with:
      slackChannel: squad-ide-private
